# Generated by Django 2.1.2 on 2018-10-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_desc',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
